/**
 * Regenerate supabase/seed.sql from the built-in fleet.
 *
 *   bun tools/gen-seed.ts
 *
 * The two used to be edited by hand and they drifted: the fleet's plates were
 * reassigned in code while the database kept the old rows, so the app showed
 * one car's name over another car's 3D model. The seed is derived now, so the
 * only way to change demo data is to change `src/lib/data.ts` and re-run this.
 */
import { writeFileSync } from "node:fs";
import { FLEET } from "../src/lib/data";

const q = (v: string | null | undefined) =>
  v === null || v === undefined ? "null" : `'${v.replace(/'/g, "''")}'`;
const b = (v: boolean) => (v ? "true" : "false");

const vehicles = FLEET.map((v) =>
  [
    q(v.regNo),
    q(v.maker),
    q(v.model),
    v.year,
    q(v.vehicleClass),
    q(v.fuel),
    q(v.emission),
    q(v.color),
    q(v.rto),
    q(v.regDate),
    q(v.chassisMasked),
    q(v.engineMasked),
    q(v.status),
    b(v.hypothecation.active),
    q(v.hypothecation.financier),
    q(v.hypothecation.since),
    b(!!v.hypothecation.form35Pending),
    q(v.insurance.insurer),
    q(v.insurance.validTill),
    q(v.puc.validTill),
    q(v.tax.paidTill),
    q(v.fitness?.validTill),
    b(v.accident.flag),
    q(v.accident.note),
    v.fairPrice.min,
    v.fairPrice.max,
    v.odometerKm,
  ].join(",")
);

const owners = FLEET.flatMap((v) =>
  v.owners.map((o) =>
    [q(v.regNo), o.serial, q(o.name), q(o.maskedName), q(o.from), q(o.to)].join(",")
  )
);

const challans = FLEET.flatMap((v) =>
  v.challans.map((c) =>
    [q(c.id), q(v.regNo), q(c.date), q(c.offense), c.amount, q(c.status)].join(",")
  )
);

const sql = `-- Synthetic demo fleet. Safe to re-run (upserts).
-- GENERATED by tools/gen-seed.ts from src/lib/data.ts — do not edit by hand.
-- No real vehicles, owners or people.

insert into public.vehicles (reg_no,maker,model,year,vehicle_class,fuel,emission,color,rto,reg_date,chassis_masked,engine_masked,status,hypo_active,hypo_financier,hypo_since,hypo_form35_pending,insurer,insurance_till,puc_till,tax_till,fitness_till,accident_flag,accident_note,fair_price_min,fair_price_max,odometer_km) values
${vehicles.map((r) => `(${r})`).join(",\n")}
on conflict (reg_no) do update set maker=excluded.maker, model=excluded.model, year=excluded.year, vehicle_class=excluded.vehicle_class, fuel=excluded.fuel, emission=excluded.emission, color=excluded.color, rto=excluded.rto, reg_date=excluded.reg_date, chassis_masked=excluded.chassis_masked, engine_masked=excluded.engine_masked, status=excluded.status, hypo_active=excluded.hypo_active, hypo_financier=excluded.hypo_financier, hypo_since=excluded.hypo_since, hypo_form35_pending=excluded.hypo_form35_pending, insurer=excluded.insurer, insurance_till=excluded.insurance_till, puc_till=excluded.puc_till, tax_till=excluded.tax_till, fitness_till=excluded.fitness_till, accident_flag=excluded.accident_flag, accident_note=excluded.accident_note, fair_price_min=excluded.fair_price_min, fair_price_max=excluded.fair_price_max, odometer_km=excluded.odometer_km;

-- Owner rows are keyed by (reg_no, serial). A car that loses an owner in the
-- fleet would leave a stale row behind, so the chain is cleared first.
delete from public.owners where reg_no in (${FLEET.map((v) => q(v.regNo)).join(",")});
insert into public.owners (reg_no,serial,name,masked_name,from_date,to_date) values
${owners.map((r) => `(${r})`).join(",\n")}
on conflict (reg_no,serial) do update set name=excluded.name, masked_name=excluded.masked_name, from_date=excluded.from_date, to_date=excluded.to_date;

delete from public.challans where reg_no in (${FLEET.map((v) => q(v.regNo)).join(",")});
insert into public.challans (id,reg_no,date,offense,amount,status) values
${challans.map((r) => `(${r})`).join(",\n")}
on conflict (id) do update set reg_no=excluded.reg_no, date=excluded.date, offense=excluded.offense, amount=excluded.amount, status=excluded.status;
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(
  `seed.sql: ${FLEET.length} vehicles, ${owners.length} owners, ${challans.length} challans`
);
